### ISSUE TITLE
Is it still being updated?

### ISSUE THREAD

**Issue by qcjxberin** [yanxiaodi/CoreMessenger#1]
Is it still being updated?

**Comment by yanxiaodi** [comment]
Hi @qcjxberin , yes I'll maintain it. Do you have any specific requirements? Let me know and see if I can help you.

**Comment by yanxiaodi** [comment]
I'm trying to add .NET 5 support at the moment.

**Comment by qcjxberin** [comment]
There is no specific requirement at present, I am looking for a suitable solution, and I am also using it under .net 5.

**Comment by yanxiaodi** [comment]
Yes .net standard 2.0 is supported in .net 5 by default. If you have any issues please let me know. Thanks.
